### ISSUE TITLE
为什么下载的是mp4文件

### ISSUE THREAD

**Issue by martjay** [ZYKsslm/BlackStone_Music_GUI#1]
还有，能不能支持下载高音质无损啥的

**Comment by ZYKsslm** [comment]
你看源码，会自动识别二进制数据并储存为相应的格式，你可以自己转成mp3，或者等我发布新版本

**Comment by ZYKsslm** [comment]
> 还有，能不能支持下载高音质无损啥的

支持的有限，等我后面发布新版本吧

**Comment by martjay** [comment]
意思是其实下载的是mv的音频是吗？

**Comment by ZYKsslm** [comment]
这我就不知道了，数据来源是接口，我只是判断接口返回的数据格式
