### ISSUE TITLE
搜索不出来东西了

### ISSUE THREAD

**Issue by martjay** [ZYKsslm/BlackStone_Music_GUI#2]
QQ音乐，今天下载了30首左右，QQ音乐就搜不出来东西了。
其他的可以搜索但是都是下载出错，只有QQ和咪咕是正常下载的，但是刚才QQ音乐搜不出东西，咪咕又资源太少。

**Comment by ZYKsslm** [comment]
你试试用未编译的源码跑一遍，然后发一下报错截图

**Comment by ZYKsslm** [comment]
q音有两个音源吧，是哪个音源

**Comment by martjay** [comment]
> q音有两个音源吧，是哪个音源

QQ会员

**Comment by martjay** [comment]
> q音有两个音源吧，是哪个音源

普通的QQ 下载失败

**Comment by ZYKsslm** [comment]
我这边跑了一下qqvip确实跟你说的一样，可能是接口的问题，等我去看看。普通qq可能是歌曲要付费所以失败

**Comment by martjay** [comment]
> 我这边跑了一下qqvip确实跟你说的一样，可能是接口的问题，等我去看看。普通qq可能是歌曲要付费所以失败

我也觉得是接口问题

**Comment by ZYKsslm** [comment]
我这边接口又恢复正常了

**Comment by martjay** [comment]
> 我这边接口又恢复正常了

确实恢复了
